status: 'dev-ready'
classBase: 'card'
flavors:
  - base
  - compact
  - empty
dependencies:
  - core/text
  - core/grid-system/index
  - core/grid-system/index/flex-spread
  - components/button-group
  - components/tables
