status: 'prototype'
classBase: 'lookup'
flavors:
  - base
  - single-select
  - multi-select
  - single-scope
  - multi-scope
  - advanced-modal
dependencies:
  - core/forms
  - core/forms/flavors/input
  - core/icons
