status: 'ga'
flavors:
  - base
  - body-small
  - heading-large
  - heading-medium
  - heading-small
  - heading-label
  - heading-label-normal
  - color
  - alignment
  - longform
  - section-title
  - section-title-dividers
