classBase: 'dropdown'
status: 'prototype'
flavors:
  - dropdown
  - dropdown-with-icons
  - dropdown-positioning
  - picklist
  - search-overflow
  - action-overflow
  - action-overflow-for-touch
dependencies:
  - helpers/text
  - core/icons
