status: 'dev-ready'
flavors:
  - automatic-sizing
  - manual-sizing
  - containers
  - horizontal-alignment-center
  - horizontal-alignment-space
  - horizontal-alignment-spread
  - vertical-alignment
  - order
dependencies:
  - helpers/sizing
