components:
  - accordion
  - activity-timeline
  - alert
  - app-launcher
  - avatar
  - badges
  - breadcrumbs
  - buttons
  - button-icons
  - button-groups
  - cards
  - checkbox
  - data-tables
  - datepickers
  - docked-composer
  - docked-form-footer
  - docked-utility-bar
  - dynamic-icons
  - feeds
  - files
  - file-selector
  - form-layout
  - global-header
  - global-navigation
  - hero-buttons
  - icons
  - input
  - list-builder
  - lookups
  - menus
  - modals
  - multi-select
  - page-headers
  - panels
  - path
  - picklist
  - pills
  - progress-bar
  - progress-indicator
  - prompt
  - popovers
  - publishers
  - radio-group
  - radio-button-group
  - rich-text-editor
  - select
  - spinners
  - split-view
  - scoped-tabs
  - tabs
  - textarea
  - tiles
  - toast
  - tooltips
  - trees
  - vertical-navigation
  - walkthrough
