classBase: 'notify'
status: 'prototype'
flavors:
  - base
  - alert
  - toast
  - prompt
  - modal-toast
dependencies:
  - components/buttons
  - components/buttons/flavors/icon
  - core/text
  - core/visibility
