scss:
  config_file: .scss-lint.yml
javascript:
  enabled: false
jscs:
  enabled: false
eslint:
  # Disabled until HoundCI updates to ESLint 2.0
  # See https://github.com/houndci/eslint/issues/18
  enabled: false
  config_file: .eslintrc.yml
ruby:
  enabled: false
