language: node_js
node_js:
  - "4.2"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rvm install 2.2.2
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
install:
  - bundle install --path vendor/bundle
  - npm install
  - npm install -g codecov
script:
  # Run "test" after "build" because the build task cleans temporary directories.
  # Build-server is a requirement for a passing travis run so keep it here. Also, must chain with && or does not guarentee successful build
  - npm run lint && npm run build && npm run test && npm run build-server
  - babel-node ./node_modules/istanbul/lib/cli cover ./node_modules/mocha/bin/_mocha -- 'test/unit/**/*.js' --compilers js:babel-register --require scripts/helpers/setup.js --recursive
  - codecov
after_success:
  - export SHA=`git rev-parse --short HEAD`
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then curl https://$VISUALTEST_USERNAME:$VISUALTEST_PASSWORD@design-system-regression-test.herokuapp.com/ci/$SHA/$TRAVIS_BRANCH ; fi
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
cache:
  directories:
    - node_modules
    - vendor/bundle
addons:
  code_climate:
    repo_token: 1035e50117ef54a8d8d028a87bdf93ad26804012105ce5ac5db3a4b4398d2fad
