language: node_js
node_js:
  - "0.12"
before_install:
  - scripts/travis/before_install.sh
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
script:
  - scripts/travis/script.sh
cache:
  directories:
    - node_modules
