language: node_js
node_js:
  - "4.2"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rvm install 2.2.2
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
install:
  - bundle install --path vendor/bundle
  - npm install
script:
  - npm run lint
  - npm run test
after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm run build-server ; fi
  - export SHA=`git rev-parse --short HEAD`
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then curl https://$VISUALTEST_USERNAME:$VISUALTEST_PASSWORD@design-system-regression-test.herokuapp.com/ci/$SHA ; fi
cache:
  directories:
    - node_modules
    - vendor/bundle
addons:
  code_climate:
    repo_token: 1035e50117ef54a8d8d028a87bdf93ad26804012105ce5ac5db3a4b4398d2fad
