language: node_js
node_js:
  - "4.2"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rvm install 2.2.2
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
install:
  - bundle install --path vendor/bundle
  - npm install
  - npm install -g codecov
script:
  - npm run build-travis
after_success:
  - export SHA=`git rev-parse HEAD`
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then curl $VISUAL_TEST_HOST/ci/$SHA/$TRAVIS_BRANCH ; fi
  - babel-node ./node_modules/istanbul/lib/cli cover ./node_modules/mocha/bin/_mocha -- 'test/{unit,integration}/**/*.js' --compilers js:babel-register --require scripts/helpers/setup.js --recursive
  - codecov
cache:
  directories:
    - node_modules
    - vendor/bundle
