language: node_js
node_js:
  - "0.12"
before_install:
  - scripts/travis/before_install.sh
install:
  - npm install
script:
  - npm run test-before && npm run prod && npm run dist && npm run test-after
after_success:
  - scripts/travis/after_success.sh
cache:
  directories:
    - node_modules
