language: node_js
node_js:
  - 6
addons:
  apt:
    packages:
      - oracle-java8-set-default
env:
  global:
    - CHROME_BIN=chromium-browser
    - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
script:
  - npm run build-travis
cache:
  directories:
    - node_modules
