status: 'dev-ready'
className: 'input'
flavors:
  - base
  - fixed-text
  - with-icon
  - with-spinner
  - read-only
  - field-level-help
lightning:
  namespace: lightning:input
  url: https://developer.salesforce.com/docs/atlas.en-us.204.0.lightning.meta/lightning/aura_compref_lightning_input.htm
