flavors:
  - input
  - textarea
  - radio
  - checkbox
  - select
  - horizontal-form
  - stacked-form
  - inline-form
  - compound-form
  - read-only-state
  - validation-state
  - sizing
  - field-level-help
