flavors:
  - input
  - textarea
  - radio
  - checkbox
  - select
  - multi-select
  - horizontal-form
  - stacked-form
  - inline-form
  - compound-form
  - read-only-state
  - validation-state
  - field-level-help
  - inline-level-help
  - edit-dialog-for-touch
