# Copyright (c) 2015-present, salesforce.com, inc. All rights reserved
# Licensed under BSD 3-Clause - see LICENSE.txt or git.io/sfdc-license

imports:
- ./deprecated/base.yml
- ./font-family.yml
- ./font-size.yml
- ./font-weight.yml
- ./illustrations.yml
- ./line-height.yml
- ./opacity.yml
- ./palette-colors.yml
- ./sizing.yml
- ./spacing.yml
- ./z-index.yml