status: 'prototype'
classBase: 'table'
flavors:
  - base
  - resizable-columns
  - responsive-overflow
  - responsive-stacked
  - responsive-stacked-horizontal
dependencies:
  - helpers/sizing
  - components/tables
