status: 'dev-ready'
dependencies:
  - components/forms/checkbox
  - components/media-objects
  - components/labels
  - components/icons
  - utilities/layout
  - utilities/themes
  - utilities/truncation
  - utilities/text
showFormFactors:
  - large
